# Generated by Django 5.0.3 on 2024-03-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='salse_id',
            new_name='sale_id',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='jhon', max_length=100),
            preserve_default=False,
        ),
    ]
